//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_IPBanUtility.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ToolTips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolTips() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF_IPBanUtility.Properties.ToolTips", typeof(ToolTips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відкрити вікно додавання нової IP-адреси до списків..
        /// </summary>
        internal static string AddIpView {
            get {
                return ResourceManager.GetString("AddIpView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адреса заблокована назавжди.
        /// </summary>
        internal static string BlackListItem {
            get {
                return ResourceManager.GetString("BlackListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копіювати до буферу обміну.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на можна додати.
        /// </summary>
        internal static string CurrentIPAddress {
            get {
                return ResourceManager.GetString("CurrentIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кількість невдалих спроб входу.
        /// </summary>
        internal static string FailedLoginCount {
            get {
                return ResourceManager.GetString("FailedLoginCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введіть адресу, яка складається з чотирьох чисел від 0 до 255, з роздільником у вигляді крапки..
        /// </summary>
        internal static string IncorrectIPAddress {
            get {
                return ResourceManager.GetString("IncorrectIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на вже додано.
        /// </summary>
        internal static string IPAddressExist {
            get {
                return ResourceManager.GetString("IPAddressExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для застосування змін служба IPBan буде перезавантажена після закриття вікна..
        /// </summary>
        internal static string ReloadIPBanService {
            get {
                return ResourceManager.GetString("ReloadIPBanService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видалити з списку заблокованих | Розблокувати.
        /// </summary>
        internal static string RemoveBlockList {
            get {
                return ResourceManager.GetString("RemoveBlockList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видалити тільки з цього з списку.
        /// </summary>
        internal static string RemoveFromList {
            get {
                return ResourceManager.GetString("RemoveFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на до чорного списку | Заблокувати назавжди.
        /// </summary>
        internal static string ToBlackList {
            get {
                return ResourceManager.GetString("ToBlackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на до білого списку | Не буде блокуватись.
        /// </summary>
        internal static string ToWiteList {
            get {
                return ResourceManager.GetString("ToWiteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Будуть перезавантажені всі списки IP-адрес..
        /// </summary>
        internal static string UpdateIPLists {
            get {
                return ResourceManager.GetString("UpdateIPLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адреса не буде блокуватись.
        /// </summary>
        internal static string WhiteListItem {
            get {
                return ResourceManager.GetString("WhiteListItem", resourceCulture);
            }
        }
    }
}
