//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_IPBanUtility.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ToolTips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolTips() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF_IPBanUtility.Properties.ToolTips", typeof(ToolTips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відкрити вікно додавання нової IP-адреси до списків..
        /// </summary>
        internal static string AddIpView {
            get {
                return ResourceManager.GetString("AddIpView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адреса заблокована назавжди.
        /// </summary>
        internal static string BlackListItem {
            get {
                return ResourceManager.GetString("BlackListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копіювати до буферу обміну.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to можна додати.
        /// </summary>
        internal static string CurrentIPAddress {
            get {
                return ResourceManager.GetString("CurrentIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість невдалих спроб входу.
        /// </summary>
        internal static string FailedLoginCount {
            get {
                return ResourceManager.GetString("FailedLoginCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть адресу, яка складається з чотирьох чисел від 0 до 255, з роздільником у вигляді крапки..
        /// </summary>
        internal static string IncorrectIPAddress {
            get {
                return ResourceManager.GetString("IncorrectIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вже додано.
        /// </summary>
        internal static string IPAddressExist {
            get {
                return ResourceManager.GetString("IPAddressExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для застосування змін служба IPBan буде перезавантажена після закриття вікна..
        /// </summary>
        internal static string ReloadIPBanService {
            get {
                return ResourceManager.GetString("ReloadIPBanService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити з списку заблокованих | Розблокувати.
        /// </summary>
        internal static string RemoveBlockList {
            get {
                return ResourceManager.GetString("RemoveBlockList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити тільки з цього з списку.
        /// </summary>
        internal static string RemoveFromList {
            get {
                return ResourceManager.GetString("RemoveFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to до чорного списку | Заблокувати назавжди.
        /// </summary>
        internal static string ToBlackList {
            get {
                return ResourceManager.GetString("ToBlackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to до білого списку | Не буде блокуватись.
        /// </summary>
        internal static string ToWiteList {
            get {
                return ResourceManager.GetString("ToWiteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будуть перезавантажені всі списки IP-адрес..
        /// </summary>
        internal static string UpdateIPLists {
            get {
                return ResourceManager.GetString("UpdateIPLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адреса не буде блокуватись.
        /// </summary>
        internal static string WhiteListItem {
            get {
                return ResourceManager.GetString("WhiteListItem", resourceCulture);
            }
        }
    }
}
